"""
Validation data loaders for Nanometa Live.

Functions for loading BLAST and minimap2 validation results from
nanometanf output, supporting both aggregate JSON and legacy tabular formats.
"""

import glob
import json
import logging
import os
from typing import Any, Dict, List, Optional

from nanometa_live.core.utils.canonical_loaders import load_canonical_validation
from nanometa_live.core.utils.sample_detector import resolve_analysis_directory


def load_validation_data(
    main_dir: str,
    sample: Optional[str] = None
) -> List[Dict[str, Any]]:
    """
    Load unified validation data (BLAST and/or minimap2) from nanometanf output.

    Checks for results in priority order:
    1. validation/validation_results.json (nanometanf aggregate output)
    2. blast_validation/validation_summary.json (legacy format)
    3. Legacy BLAST tabular files (fallback)

    Args:
        main_dir: Main nanometanf output directory
        sample: Sample name to filter by, or None/"All Samples" for all

    Returns:
        List of ValidationResult.to_dict() entries with both BLAST and
        minimap2 results (each as a separate entry with validation_method field)
    """
    from nanometa_live.core.parsers.blast_validation_parser import ValidationParser

    main_dir = resolve_analysis_directory(main_dir)
    parser = ValidationParser(main_dir)

    filter_sample = None if (sample is None or sample == "All Samples") else sample
    results = parser.get_validation_results(sample=filter_sample)

    return [r.to_dict() for r in results]


def load_blast_validation_data(
    main_dir: str,
    watchlist: List[Dict[str, Any]],
    sample: Optional[str] = None
) -> Dict[int, Dict[str, Any]]:
    """
    Load BLAST validation data for watched species.

    BLAST validation files are generated by nanometanf when blast_validation is
    enabled. Files are named {sample}_{taxid}.txt or {taxid}.txt in BLAST
    tabular format (outfmt 6).

    Args:
        main_dir: Main nanometanf output directory
        watchlist: List of watched species dicts with 'name' and 'taxid' keys
        sample: Sample name to filter by, or None/"All Samples" for aggregated

    Returns:
        Dictionary mapping taxid to validation stats:
        {
            562: {
                'taxid': 562,
                'name': 'Escherichia coli',
                'total_reads': 1452,
                'validated_reads': 1234,
                'validation_rate': 85.0,
                'status': 'validated'  # 'validated', 'partial', 'failed', 'no_data'
            },
            ...
        }
    """
    # Import here to avoid circular imports
    from nanometa_live.core.utils.classification_loaders import load_kraken_data

    # Auto-resolve to analysis directory if needed
    main_dir = resolve_analysis_directory(main_dir)

    # Try canonical validation first (waterfall pattern)
    canonical_data = load_canonical_validation(main_dir)
    if canonical_data is not None:
        logging.debug("Using canonical validation results")
        results = {}
        filter_sample = None if (sample is None or sample == "All Samples") else sample

        for sample_id, taxid_entries in canonical_data.get("results", {}).items():
            if filter_sample and sample_id != filter_sample:
                continue
            for tid_str, entry in taxid_entries.items():
                tid = int(tid_str)
                watchlist_match = None
                for s in watchlist:
                    if s.get("taxid") and int(s["taxid"]) == tid:
                        watchlist_match = s
                        break
                if not watchlist_match:
                    continue

                hit_rate = entry.get("hit_rate", 0.0)
                result_entry = {
                    "taxid": tid,
                    "name": watchlist_match.get("name", f"Species {tid}"),
                    "total_reads": entry.get("kraken_reads", 0),
                    "validated_reads": entry.get("blast_hits", entry.get("mapped_reads", 0)),
                    "validation_rate": round(
                        hit_rate * 100 if hit_rate <= 1.0 else hit_rate, 1
                    ),
                    "status": entry.get("status", "no_data"),
                    "avg_identity": entry.get("avg_identity", 0.0),
                }
                # Map status values
                status_map = {"confirmed": "validated", "uncertain": "partial", "rejected": "failed"}
                result_entry["status"] = status_map.get(result_entry["status"], result_entry["status"])

                results[tid] = result_entry

        if results:
            return results

    # First check for nanometanf aggregate validation JSON (includes both BLAST and minimap2)
    aggregate_paths = [
        os.path.join(main_dir, "validation", "validation_results.json"),
        os.path.join(main_dir, "blast_validation", "validation_results.json"),
    ]

    for agg_path in aggregate_paths:
        try:
            with open(agg_path, 'r') as f:
                agg_data = json.load(f)

            results = {}
            filter_sample = None if (sample is None or sample == "All Samples") else sample

            for sample_id, taxid_entries in agg_data.get('results', {}).items():
                if filter_sample and sample_id != filter_sample:
                    continue
                for tid_str, entry in taxid_entries.items():
                    tid = int(tid_str)
                    # Check if this taxid is in the watchlist
                    watchlist_match = None
                    for s in watchlist:
                        if s.get('taxid') and int(s['taxid']) == tid:
                            watchlist_match = s
                            break
                    if not watchlist_match:
                        continue

                    # BLAST data
                    blast_hits = entry.get('blast_hits', 0)
                    hit_rate = entry.get('hit_rate', 0.0)
                    kraken_reads = entry.get('kraken_reads', 0)

                    result_entry = {
                        'taxid': tid,
                        'name': watchlist_match.get('name', f'Species {tid}'),
                        'total_reads': kraken_reads,
                        'validated_reads': blast_hits,
                        'validation_rate': round(hit_rate * 100 if hit_rate <= 1.0 else hit_rate, 1),
                        'status': entry.get('validation_status', 'no_data'),
                        'avg_identity': entry.get('avg_identity', 0.0),
                    }

                    # Map status values
                    if result_entry['status'] == 'confirmed':
                        result_entry['status'] = 'validated'
                    elif result_entry['status'] == 'uncertain':
                        result_entry['status'] = 'partial'
                    elif result_entry['status'] == 'rejected':
                        result_entry['status'] = 'failed'

                    # Add minimap2 fields if present
                    if entry.get('minimap2_mapped') is not None:
                        result_entry['minimap2_validated_reads'] = int(entry.get('minimap2_mapped', 0))
                        mm2_rate = entry.get('minimap2_hit_rate', 0.0)
                        result_entry['minimap2_validation_rate'] = round(
                            mm2_rate * 100 if mm2_rate <= 1.0 else mm2_rate, 1
                        )
                        result_entry['minimap2_identity'] = float(entry.get('minimap2_identity', 0.0))
                        result_entry['minimap2_avg_mapq'] = float(entry.get('avg_mapq', 0.0))
                        result_entry['minimap2_status'] = entry.get('minimap2_status', 'no_data')

                    results[tid] = result_entry

            if results:
                logging.info(f"Loaded validation data from aggregate JSON: {len(results)} entries")
                return results
        except (FileNotFoundError, OSError):
            continue  # File was deleted or inaccessible
        except json.JSONDecodeError as e:
            logging.warning(f"Malformed aggregate validation JSON {agg_path}: {e}")
        except (ValueError, KeyError, TypeError) as e:
            logging.warning(f"Unexpected content in aggregate validation JSON {agg_path}: {e}")

    # nanometanf v1.1+ publishes BLAST results to validation/blast/
    blast_dir = os.path.join(main_dir, "validation", "blast")

    # Fallback to legacy directory names
    if not os.path.exists(blast_dir):
        blast_dir = os.path.join(main_dir, "blast_validation")
    if not os.path.exists(blast_dir):
        blast_dir = os.path.join(main_dir, "blast")
    if not os.path.exists(blast_dir):
        logging.debug("BLAST validation directory not found")
        return {}

    # OPTIMIZATION: Load Kraken data ONCE outside the loop (was loading per-species)
    # This provides ~50x speedup for typical watchlists with 50+ species
    kraken_df = load_kraken_data(main_dir, sample)

    results = {}

    for species in watchlist:
        taxid = species.get('taxid')
        name = species.get('name', f'Species {taxid}')

        if taxid is None:
            continue

        # Convert taxid to int if string
        try:
            taxid = int(taxid)
        except (ValueError, TypeError):
            logging.warning(f"Invalid taxid: {taxid}")
            continue

        # Find BLAST result files for this taxid
        blast_files = []

        if sample is None or sample == "All Samples":
            # Look for all files matching this taxid
            # Supports both legacy .txt and nanometanf .blast.tsv extensions
            patterns = [
                os.path.join(blast_dir, f"*_{taxid}.txt"),
                os.path.join(blast_dir, f"{taxid}.txt"),
                os.path.join(blast_dir, f"*_{taxid}_blast.txt"),
                os.path.join(blast_dir, f"*_{taxid}.blast.tsv"),
            ]
            for pattern in patterns:
                blast_files.extend(glob.glob(pattern))
        else:
            # Look for sample-specific file
            # Supports both legacy .txt and nanometanf .blast.tsv extensions
            patterns = [
                os.path.join(blast_dir, f"{sample}_{taxid}.txt"),
                os.path.join(blast_dir, f"{sample}_{taxid}_blast.txt"),
                os.path.join(blast_dir, f"{sample}_{taxid}.blast.tsv"),
            ]
            for pattern in patterns:
                blast_files.append(pattern)

        # Count validated reads from all matching files
        unique_reads = set()

        for blast_file in blast_files:
            try:
                with open(blast_file, 'r') as f:
                    for line in f:
                        if line.strip():
                            parts = line.strip().split('\t')
                            if parts:
                                unique_reads.add(parts[0])
            except (FileNotFoundError, OSError):
                continue  # File was deleted or inaccessible
            except UnicodeDecodeError as e:
                logging.warning(f"BLAST file is not valid text {blast_file}: {e}")
                continue

        validated_count = len(unique_reads)

        # Get total reads for this species from pre-loaded Kraken data
        total_reads = 0

        if not kraken_df.empty:
            species_row = kraken_df[kraken_df['taxid'] == taxid]
            if not species_row.empty:
                total_reads = int(species_row.iloc[0]['reads'])

        # Calculate validation rate
        if total_reads > 0:
            validation_rate = (validated_count / total_reads) * 100
        else:
            validation_rate = 0.0

        # Determine validation status
        if validated_count == 0 and not blast_files:
            status = 'no_data'
        elif validation_rate >= 80:
            status = 'validated'
        elif validation_rate >= 50:
            status = 'partial'
        else:
            status = 'failed'

        results[taxid] = {
            'taxid': taxid,
            'name': name,
            'total_reads': total_reads,
            'validated_reads': validated_count,
            'validation_rate': round(validation_rate, 1),
            'status': status
        }

    return results
