"""
Data processor for Nanometa Live.

This module handles the processing of data files generated by the workflow,
transforming raw output into the formats needed for visualization.
"""

import os
import pandas as pd
import numpy as np
import logging
from typing import Dict, Any, List, Optional, Tuple


class DataProcessor:
    """
    Processes workflow output data for visualization and analysis.
    """

    def __init__(self, project_dir: str):
        """
        Initialize the data processor.

        Args:
            project_dir: Directory containing the project data
        """
        self.project_dir = project_dir
        self.kraken_report_path = os.path.join(
            project_dir, "kraken_cumul/kraken_cumul_report.kreport2"
        )
        self.qc_data_path = os.path.join(project_dir, "qc_data/cumul_qc.txt")
        self.fastp_data_path = os.path.join(
            project_dir, "fastp_reports/compiled_fastp.txt"
        )
        self.blast_dir = os.path.join(project_dir, "blast_result_files")

    def check_data_available(self) -> bool:
        """
        Check if output data is available for processing.

        Returns:
            True if data is available, False otherwise
        """
        return (
            os.path.exists(self.kraken_report_path)
            and os.path.getsize(self.kraken_report_path) > 0
        )

    def get_species_of_interest_data(
        self, species_list: List[Dict[str, str]], threshold: int = 100
    ) -> Tuple[pd.DataFrame, Any]:
        """
        Process data for species of interest.

        Args:
            species_list: List of species to include
            threshold: Read count threshold for highlighting

        Returns:
            DataFrame with species data and a Plotly figure
        """
        if not self.check_data_available():
            return pd.DataFrame(), None

        try:
            # Load the Kraken report
            kraken_df = pd.read_csv(
                self.kraken_report_path,
                sep="\t",
                header=None,
                names=["%", "cumul_reads", "reads", "rank", "taxid", "name"],
            )

            # Extract only the species of interest
            result_rows = []
            for species in species_list:
                taxid = species.get("taxid", "")
                if not taxid:
                    continue

                # Find this taxid in the Kraken report
                matches = kraken_df[kraken_df["taxid"] == taxid]
                if matches.empty:
                    # Species not found in data
                    result_rows.append(
                        {
                            "Name": species.get("name", "Unknown"),
                            "Tax ID": taxid,
                            "Reads": 0,
                            "Percent": 0.0,
                            "Color": "Green",
                        }
                    )
                else:
                    # Species found
                    row = matches.iloc[0]
                    result_rows.append(
                        {
                            "Name": row["name"].strip(),
                            "Tax ID": row["taxid"],
                            "Reads": int(row["reads"]),
                            "Percent": float(row["%"]),
                            "Color": (
                                "Red" if int(row["reads"]) > threshold else "Green"
                            ),
                        }
                    )

            # Sort by read count
            result_rows = sorted(result_rows, key=lambda x: x["Reads"], reverse=True)

            # Create DataFrame
            df = pd.DataFrame(result_rows)

            # Add validation data if available
            if os.path.exists(self.blast_dir):
                validated = []
                for row in result_rows:
                    taxid = row["Tax ID"]
                    blast_file = os.path.join(self.blast_dir, f"{taxid}.txt")
                    if os.path.exists(blast_file) and os.path.getsize(blast_file) > 0:
                        # Count unique sequences in BLAST results
                        try:
                            blast_df = pd.read_csv(blast_file, sep="\t", header=None)
                            val_count = blast_df[0].nunique()
                        except:
                            val_count = 0
                    else:
                        val_count = 0
                    validated.append(val_count)

                if df.shape[0] > 0:  # Only add if DataFrame has rows
                    df["Validated"] = validated

            # Create plot
            import plotly.express as px

            if not df.empty:
                fig = px.bar(
                    df,
                    x="Name",
                    y="Reads",
                    color="Color",
                    title="Species of Interest",
                    labels={"Reads": "Number of Reads", "Name": "Species"},
                    color_discrete_map={"Red": "red", "Green": "green"},
                )

                # Format the plot
                fig.update_layout(showlegend=False, xaxis_tickangle=-45, height=400)

                # Add validated reads if available
                if "Validated" in df.columns:
                    fig.add_trace(
                        px.bar(
                            df,
                            x="Name",
                            y="Validated",
                            color_discrete_sequence=["blue"],
                        ).data[0]
                    )
                    fig.update_layout(barmode="group")
            else:
                fig = px.bar(title="Species of Interest - No Data")

            return df, fig

        except Exception as e:
            logging.error(f"Error processing species of interest data: {e}")
            return pd.DataFrame(), None

    def get_top_matches(
        self,
        num_entries: int = 20,
        tax_levels: List[str] = None,
        domains: List[str] = None,
    ) -> pd.DataFrame:
        """
        Get the top taxonomic matches.

        Args:
            num_entries: Number of entries to include
            tax_levels: Taxonomic levels to include
            domains: Domains to include

        Returns:
            DataFrame with top matches
        """
        if not self.check_data_available():
            return pd.DataFrame()

        if tax_levels is None:
            tax_levels = ["S"]  # Default to species level

        if domains is None:
            domains = [
                "Bacteria",
                "Archaea",
                "Eukaryota",
                "Viruses",
            ]  # Default to all domains

        try:
            # Load the Kraken report
            kraken_df = pd.read_csv(
                self.kraken_report_path,
                sep="\t",
                header=None,
                names=["%", "cumul_reads", "reads", "rank", "taxid", "name"],
            )

            # Filter for domains
            domain_indices = []
            for domain in domains:
                domain_data = kraken_df[kraken_df["name"].str.strip() == domain]
                if not domain_data.empty:
                    domain_idx = domain_data.index[0]

                    # Find next domain index
                    next_domains = kraken_df.iloc[domain_idx + 1 :][
                        kraken_df["name"].isin(domains)
                    ]
                    if not next_domains.empty:
                        next_idx = next_domains.index[0]
                    else:
                        next_idx = len(kraken_df)

                    # Add all indices for this domain
                    domain_indices.extend(range(domain_idx, next_idx))

            # Filter by domains and tax levels
            filtered_df = kraken_df.iloc[domain_indices]
            filtered_df = filtered_df[filtered_df["rank"].isin(tax_levels)]

            # Sort by reads
            filtered_df = filtered_df.sort_values("reads", ascending=False)

            # Take top entries
            top_df = filtered_df.head(num_entries).copy()

            # Add index column and clean up names
            top_df["Index"] = range(1, len(top_df) + 1)
            top_df["name"] = top_df["name"].str.strip()

            # Prepare result
            result_data = []
            for _, row in top_df.iterrows():
                result_data.append(
                    {
                        "Index": int(row["Index"]),
                        "Name": row["name"],
                        "Tax ID": row["taxid"],
                        "Tax Rank": row["rank"],
                        "Reads": int(row["reads"]),
                    }
                )

            return pd.DataFrame(result_data)

        except Exception as e:
            logging.error(f"Error processing top matches: {e}")
            return pd.DataFrame()

    def get_qc_data(self) -> Tuple[Dict[str, Any], List[Any]]:
        """
        Get quality control data.

        Returns:
            Tuple of (stats dictionary, list of plot figures)
        """
        try:
            # Initialize variables
            stats = {
                "total_reads_pre_filtering": 0,
                "passed_filter_reads": 0,
                "low_quality_reads": 0,
                "too_many_N_reads": 0,
                "too_short_reads": 0,
                "total_removed_reads": 0,
                "classified_reads": 0,
                "unclassified_reads": 0,
                "files_processed": 0,
                "files_waiting": 0,
            }

            # QC data from cumul_qc.txt
            if os.path.exists(self.qc_data_path):
                qc_df = pd.read_csv(self.qc_data_path, names=["Time", "Reads", "Bp"])
                stats["total_reads_pre_filtering"] = qc_df["Reads"].sum()
                stats["files_processed"] = len(qc_df)

                # Convert time column to datetime for plotting
                qc_df["Time"] = pd.to_datetime(qc_df["Time"])
                qc_df = qc_df.sort_values("Time")

                # Calculate cumulative values
                qc_df["Cumulative Reads"] = qc_df["Reads"].cumsum()
                qc_df["Cumulative Bp"] = qc_df["Bp"].cumsum()
            else:
                # Create empty DataFrame
                qc_df = pd.DataFrame(
                    columns=["Time", "Reads", "Bp", "Cumulative Reads", "Cumulative Bp"]
                )

            # FastP data from compiled_fastp.txt
            if os.path.exists(self.fastp_data_path):
                fastp_df = pd.read_csv(
                    self.fastp_data_path,
                    names=[
                        "passed_filter_reads",
                        "low_quality_reads",
                        "too_many_N_reads",
                        "too_short_reads",
                    ],
                )

                stats["passed_filter_reads"] = fastp_df["passed_filter_reads"].sum()
                stats["low_quality_reads"] = fastp_df["low_quality_reads"].sum()
                stats["too_many_N_reads"] = fastp_df["too_many_N_reads"].sum()
                stats["too_short_reads"] = fastp_df["too_short_reads"].sum()
                stats["total_removed_reads"] = (
                    stats["low_quality_reads"]
                    + stats["too_many_N_reads"]
                    + stats["too_short_reads"]
                )

            # Kraken classification data
            if os.path.exists(self.kraken_report_path):
                kraken_df = pd.read_csv(
                    self.kraken_report_path,
                    sep="\t",
                    header=None,
                    names=["%", "cumul_reads", "reads", "rank", "taxid", "name"],
                )

                # Unclassified reads are in first row (taxid 0)
                unclassified_row = kraken_df[kraken_df["taxid"] == 0]
                if not unclassified_row.empty:
                    stats["unclassified_reads"] = int(unclassified_row.iloc[0]["reads"])

                # Classified reads are the sum of all other rows
                stats["classified_reads"] = int(
                    kraken_df["reads"].sum() - stats["unclassified_reads"]
                )

            # Calculate percentages
            if stats["total_reads_pre_filtering"] > 0:
                stats["percent_passed"] = round(
                    (stats["passed_filter_reads"] * 100)
                    / stats["total_reads_pre_filtering"],
                    1,
                )
                stats["percent_removed"] = round(
                    (stats["total_removed_reads"] * 100)
                    / stats["total_reads_pre_filtering"],
                    1,
                )
            else:
                stats["percent_passed"] = 0
                stats["percent_removed"] = 0

            if stats["total_removed_reads"] > 0:
                stats["percent_low_quality"] = round(
                    (stats["low_quality_reads"] * 100) / stats["total_removed_reads"], 1
                )
                stats["percent_too_many_N"] = round(
                    (stats["too_many_N_reads"] * 100) / stats["total_removed_reads"], 1
                )
                stats["percent_too_short"] = round(
                    (stats["too_short_reads"] * 100) / stats["total_removed_reads"], 1
                )
            else:
                stats["percent_low_quality"] = 0
                stats["percent_too_many_N"] = 0
                stats["percent_too_short"] = 0

            total_kraken_reads = stats["classified_reads"] + stats["unclassified_reads"]
            if total_kraken_reads > 0:
                stats["percent_classified"] = round(
                    (stats["classified_reads"] * 100) / total_kraken_reads, 1
                )
                stats["percent_unclassified"] = round(
                    (stats["unclassified_reads"] * 100) / total_kraken_reads, 1
                )
            else:
                stats["percent_classified"] = 0
                stats["percent_unclassified"] = 0

            # Create plots
            import plotly.express as px

            if not qc_df.empty:
                # Format time for display
                time_for_display = qc_df["Time"].dt.strftime("%Y-%m-%d %H:%M:%S")
                time_for_barplots = qc_df["Time"].dt.strftime("%H:%M:%S")

                # Cumulative reads plot
                cumul_reads_fig = px.line(
                    qc_df,
                    x=time_for_display,
                    y="Cumulative Reads",
                    title="Cumulative Reads Over Time",
                )

                # Cumulative base pairs plot
                cumul_bp_fig = px.line(
                    qc_df,
                    x=time_for_display,
                    y="Cumulative Bp",
                    title="Cumulative Base Pairs Over Time",
                )

                # Reads per batch plot
                reads_fig = px.bar(
                    qc_df, x=time_for_barplots, y="Reads", title="Reads per Batch"
                )

                # Base pairs per batch plot
                bp_fig = px.bar(
                    qc_df, x=time_for_barplots, y="Bp", title="Base Pairs per Batch"
                )

                # Update layouts
                for fig in [cumul_reads_fig, cumul_bp_fig, reads_fig, bp_fig]:
                    fig.update_layout(height=350, margin=dict(l=50, r=50, t=50, b=50))

                # Update x-axis labels for bar plots
                reads_fig.update_xaxes(title_text="Batch Timestamp")
                bp_fig.update_xaxes(title_text="Batch Timestamp")

                # Make bar plots discrete
                reads_fig.update_xaxes(type="category")
                bp_fig.update_xaxes(type="category")

            else:
                # Create empty plots
                cumul_reads_fig = px.line(title="Cumulative Reads - No Data")
                cumul_bp_fig = px.line(title="Cumulative Base Pairs - No Data")
                reads_fig = px.bar(title="Reads per Batch - No Data")
                bp_fig = px.bar(title="Base Pairs per Batch - No Data")

            plots = [cumul_reads_fig, cumul_bp_fig, reads_fig, bp_fig]

            return stats, plots

        except Exception as e:
            logging.error(f"Error processing QC data: {e}")
            return {}, []

    def get_sankey_data(
        self, domains: List[str], tax_levels: List[str], top_n: int = 10
    ) -> Any:
        """
        Process data for Sankey plot.

        Args:
            domains: Domains to include
            tax_levels: Taxonomy levels to include
            top_n: Number of top entries per level

        Returns:
            Plotly Sankey figure
        """
        import plotly.graph_objects as go

        if not self.check_data_available():
            # Return placeholder
            link = dict(source=[0], target=[1], value=[1])
            node = dict(label=["Waiting for data", "No data"], pad=25, thickness=10)
            return go.Sankey(link=link, node=node)

        try:
            # Load the Kraken report
            kraken_df = pd.read_csv(
                self.kraken_report_path,
                sep="\t",
                header=None,
                names=["%", "cumul_reads", "reads", "rank", "taxid", "name"],
            )

            # Define domain filtering function
            def filter_by_domains(df, domains):
                domain_indices = []
                for domain in domains:
                    domain_data = df[df["name"].str.strip() == domain]
                    if not domain_data.empty:
                        domain_idx = domain_data.index[0]

                        # Find next domain's index
                        next_domains = df.iloc[domain_idx + 1 :][
                            df["name"].isin(domains)
                        ]
                        if not next_domains.empty:
                            next_idx = next_domains.index[0]
                        else:
                            next_idx = len(df)

                        # Add all indices for this domain
                        domain_indices.extend(range(domain_idx, next_idx))

                return df.iloc[domain_indices]

            # Filter by domains
            filtered_df = filter_by_domains(kraken_df, domains)

            # Create node matrix
            def create_node_matrix(df, tax_levels):
                node_map = {}
                node_labels = []
                node_id = 0

                for level in tax_levels:
                    level_df = df[df["rank"] == level]
                    for _, row in level_df.iterrows():
                        name = row["name"].strip()
                        if name not in node_map:
                            node_map[name] = node_id
                            node_labels.append(name)
                            node_id += 1

                return node_map, node_labels

            # Create edge data
            def create_edges(df, node_map, tax_levels, top_n):
                edges = []

                # For each tax level (except the highest)
                for i in range(len(tax_levels) - 1):
                    lower_level = tax_levels[i]
                    higher_level = tax_levels[i + 1]

                    # Get rows for the lower level
                    lower_df = (
                        df[df["rank"] == lower_level]
                        .sort_values("reads", ascending=False)
                        .head(top_n)
                    )

                    for _, lower_row in lower_df.iterrows():
                        lower_name = lower_row["name"].strip()
                        lower_id = node_map.get(lower_name)

                        if lower_id is None:
                            continue

                        # Find the parent in the hierarchy
                        parent_idx = None
                        for j in range(lower_row.name + 1, len(df)):
                            if df.iloc[j]["rank"] == higher_level:
                                parent_idx = j
                                break

                        if parent_idx is not None:
                            parent_name = df.iloc[parent_idx]["name"].strip()
                            parent_id = node_map.get(parent_name)

                            if parent_id is not None:
                                edges.append(
                                    {
                                        "source": parent_id,
                                        "target": lower_id,
                                        "value": int(lower_row["reads"]),
                                    }
                                )

                return edges

            # Create Sankey data
            node_map, node_labels = create_node_matrix(filtered_df, tax_levels)
            edges = create_edges(filtered_df, node_map, tax_levels, top_n)

            # Format for Plotly
            link = dict(
                source=[edge["source"] for edge in edges],
                target=[edge["target"] for edge in edges],
                value=[edge["value"] for edge in edges],
            )

            node = dict(label=node_labels, pad=25, thickness=10, color="blue")

            sankey = go.Sankey(link=link, node=node)

            return sankey

        except Exception as e:
            logging.error(f"Error processing Sankey data: {e}")
            # Return placeholder
            link = dict(source=[0], target=[1], value=[1])
            node = dict(label=["Error", str(e)], pad=25, thickness=10)
            return go.Sankey(link=link, node=node)

    def get_sunburst_data(self, domains: List[str], min_reads: int = 10) -> Any:
        """
        Process data for Sunburst chart.

        Args:
            domains: Domains to include
            min_reads: Minimum number of reads for inclusion

        Returns:
            Plotly Sunburst figure
        """
        import plotly.express as px

        if not self.check_data_available():
            return px.sunburst(
                names=["No data"], parents=[""], values=[1], title="Waiting for data"
            )

        try:
            # Load the Kraken report
            kraken_df = pd.read_csv(
                self.kraken_report_path,
                sep="\t",
                header=None,
                names=["%", "cumul_reads", "reads", "rank", "taxid", "name"],
            )

            # Filter by domains
            domain_indices = []
            for domain in domains:
                domain_data = kraken_df[kraken_df["name"].str.strip() == domain]
                if not domain_data.empty:
                    domain_idx = domain_data.index[0]

                    # Find next domain's index
                    next_domains = kraken_df.iloc[domain_idx + 1 :][
                        kraken_df["name"].isin(domains)
                    ]
                    if not next_domains.empty:
                        next_idx = next_domains.index[0]
                    else:
                        next_idx = len(kraken_df)

                    # Add all indices for this domain
                    domain_indices.extend(range(domain_idx, next_idx))

            filtered_df = kraken_df.iloc[domain_indices]

            # Filter by min reads
            filtered_df = filtered_df[filtered_df["reads"] > min_reads]

            # Prepare data for sunburst
            taxons = []
            parents = []
            values = []

            # Add root
            taxons.append("root")
            parents.append("")
            values.append(0)

            # Function to find parent
            def find_parent(row_idx, df):
                row_level = df.iloc[row_idx]["name"].count("  ") // 2
                if row_level == 0:  # Domain level
                    return "root"

                # Look up until we find the parent
                for i in range(row_idx - 1, -1, -1):
                    parent_level = df.iloc[i]["name"].count("  ") // 2
                    if parent_level == row_level - 1:
                        return df.iloc[i]["name"].strip()

                return "root"  # Default to root if no parent found

            # Process each row
            for i, row in filtered_df.iterrows():
                name = row["name"].strip()
                parent = find_parent(i, filtered_df)
                value = row["reads"]

                taxons.append(name)
                parents.append(parent)
                values.append(value)

            # Create sunburst chart
            sunburst = px.sunburst(
                names=taxons,
                parents=parents,
                values=values,
                color=values,
                color_continuous_scale="Jet",
                title="Taxonomic Classification",
            )

            sunburst.update_traces(hovertemplate="<b>%{label}</b><br>Reads: %{value}")

            return sunburst

        except Exception as e:
            logging.error(f"Error processing Sunburst data: {e}")
            return px.sunburst(
                names=["Error"], parents=[""], values=[1], title=f"Error: {str(e)}"
            )
