"""
NanometanfOutputParser: Comprehensive parser for nanometanf v1.1.0 pipeline outputs.

This module provides parsers for all nanometanf output formats including:
- MultiQC aggregated reports
- Kraken2 taxonomic classification
- FASTP quality control metrics
- BLAST validation results
- Real-time batch statistics

Author: Nanometa Live Development Team
"""

import os
import json
import glob
import time
import logging
import threading
import re
from typing import Dict, Any, List, Tuple, Optional, Callable
from pathlib import Path
import pandas as pd
import numpy as np


# Configure logging
logger = logging.getLogger(__name__)


class NanometanfOutputParser:
    """
    Main parser for all nanometanf v1.1.0 pipeline outputs.

    This class provides comprehensive parsing capabilities for various output formats
    generated by the nanometanf pipeline, including quality control metrics,
    taxonomic classification results, and real-time batch statistics.

    Attributes:
        outdir (Path): Pipeline output directory
        multiqc_dir (Path): MultiQC output subdirectory
        fastp_dir (Path): FASTP output subdirectory
        kraken2_dir (Path): Kraken2 output subdirectory
        blast_dir (Path): BLAST output subdirectory
        realtime_batch_dir (Path): Real-time batch statistics subdirectory
    """

    def __init__(self, outdir: str):
        """
        Initialize the parser with the pipeline output directory.

        Args:
            outdir: Path to the nanometanf pipeline output directory
        """
        self.outdir = Path(outdir)

        # Set up subdirectory paths following nanometanf structure
        self.multiqc_dir = self.outdir / "multiqc"
        self.fastp_dir = self.outdir / "fastp"
        self.kraken2_dir = self.outdir / "kraken2"
        self.blast_dir = self.outdir / "validation" / "blast"
        self.realtime_batch_dir = self.outdir / "realtime_batch_stats"
        self.nanoplot_dir = self.outdir / "nanoplot"

        logger.info(f"Initialized NanometanfOutputParser with outdir: {self.outdir}")

    # ==================== Utility Methods ====================

    def file_exists_with_retry(self, path: str, retries: int = 3, delay: float = 0.5) -> bool:
        """
        Check if file exists with retry logic for file watching robustness.

        This method handles race conditions in real-time monitoring where files
        may be in the process of being written.

        Args:
            path: File path to check
            retries: Number of retry attempts
            delay: Delay between retries in seconds

        Returns:
            True if file exists and is readable, False otherwise
        """
        file_path = Path(path)

        for attempt in range(retries):
            if file_path.exists() and file_path.is_file():
                try:
                    # Try to open the file to ensure it's readable
                    with open(file_path, 'r') as f:
                        f.read(1)
                    return True
                except (IOError, OSError) as e:
                    logger.debug(f"File not yet readable (attempt {attempt + 1}/{retries}): {e}")
                    if attempt < retries - 1:
                        time.sleep(delay)
            else:
                if attempt < retries - 1:
                    time.sleep(delay)

        return False

    # ==================== MultiQC Parsers ====================

    def parse_multiqc_general_stats(self) -> pd.DataFrame:
        """
        Parse MultiQC general statistics table.

        Returns sample-level statistics aggregated across all QC tools.

        Returns:
            DataFrame with sample-level statistics, or empty DataFrame if not found
        """
        general_stats_path = self.multiqc_dir / "multiqc_data" / "multiqc_general_stats.txt"

        try:
            if not self.file_exists_with_retry(str(general_stats_path)):
                logger.warning(f"MultiQC general stats not found: {general_stats_path}")
                return pd.DataFrame()

            df = pd.read_csv(general_stats_path, sep='\t', index_col=0)
            logger.info(f"Parsed MultiQC general stats: {len(df)} samples")
            return df

        except Exception as e:
            logger.error(f"Error parsing MultiQC general stats: {e}")
            return pd.DataFrame()

    def parse_multiqc_json(self) -> Dict[str, Any]:
        """
        Parse complete MultiQC JSON data structure.

        Returns the full MultiQC data structure including all module outputs,
        plot data, and configuration.

        Returns:
            Dictionary with complete MultiQC data, or empty dict if not found
        """
        multiqc_json_path = self.multiqc_dir / "multiqc_data" / "multiqc_data.json"

        try:
            if not self.file_exists_with_retry(str(multiqc_json_path)):
                logger.warning(f"MultiQC JSON not found: {multiqc_json_path}")
                return {}

            with open(multiqc_json_path, 'r') as f:
                data = json.load(f)

            logger.info(f"Parsed MultiQC JSON with {len(data.get('report_plot_data', {}))} plot datasets")
            return data

        except Exception as e:
            logger.error(f"Error parsing MultiQC JSON: {e}")
            return {}

    def parse_multiqc_fastp_data(self) -> pd.DataFrame:
        """
        Parse MultiQC aggregated FASTP data.

        Extracts FASTP-specific data from MultiQC outputs, including
        filtering statistics and quality metrics.

        Returns:
            DataFrame with FASTP aggregated data, or empty DataFrame if not found
        """
        fastp_data_path = self.multiqc_dir / "multiqc_data" / "multiqc_fastp.txt"

        try:
            if not self.file_exists_with_retry(str(fastp_data_path)):
                logger.warning(f"MultiQC FASTP data not found: {fastp_data_path}")
                # Try to extract from JSON
                multiqc_data = self.parse_multiqc_json()
                if 'report_saved_raw_data' in multiqc_data:
                    fastp_data = multiqc_data['report_saved_raw_data'].get('multiqc_fastp', {})
                    if fastp_data:
                        df = pd.DataFrame.from_dict(fastp_data, orient='index')
                        logger.info(f"Extracted FASTP data from JSON: {len(df)} samples")
                        return df
                return pd.DataFrame()

            df = pd.read_csv(fastp_data_path, sep='\t', index_col=0)
            logger.info(f"Parsed MultiQC FASTP data: {len(df)} samples")
            return df

        except Exception as e:
            logger.error(f"Error parsing MultiQC FASTP data: {e}")
            return pd.DataFrame()

    def parse_multiqc_kraken_data(self) -> pd.DataFrame:
        """
        Parse MultiQC aggregated Kraken2 data.

        Extracts Kraken2-specific data from MultiQC outputs, including
        classification rates and top species assignments.

        Returns:
            DataFrame with Kraken2 aggregated data, or empty DataFrame if not found
        """
        kraken_data_path = self.multiqc_dir / "multiqc_data" / "multiqc_kraken.txt"

        try:
            if not self.file_exists_with_retry(str(kraken_data_path)):
                logger.warning(f"MultiQC Kraken2 data not found: {kraken_data_path}")
                # Try to extract from JSON
                multiqc_data = self.parse_multiqc_json()
                if 'report_saved_raw_data' in multiqc_data:
                    kraken_data = multiqc_data['report_saved_raw_data'].get('multiqc_kraken', {})
                    if kraken_data:
                        df = pd.DataFrame.from_dict(kraken_data, orient='index')
                        logger.info(f"Extracted Kraken2 data from JSON: {len(df)} samples")
                        return df
                return pd.DataFrame()

            df = pd.read_csv(kraken_data_path, sep='\t', index_col=0)
            logger.info(f"Parsed MultiQC Kraken2 data: {len(df)} samples")
            return df

        except Exception as e:
            logger.error(f"Error parsing MultiQC Kraken2 data: {e}")
            return pd.DataFrame()

    # ==================== Kraken2 Parsers ====================

    def parse_kraken_report(self, sample: str) -> pd.DataFrame:
        """
        Parse Kraken2 report file for a specific sample.

        The Kraken2 report format contains 6 tab-separated columns:
        1. Percentage of reads covered by clade
        2. Number of reads covered by clade
        3. Number of reads assigned directly to taxon
        4. Rank code (U, R, D, K, P, C, O, F, G, S)
        5. NCBI taxonomy ID
        6. Scientific name (indented by rank)

        Args:
            sample: Sample name

        Returns:
            DataFrame with columns: percent, reads_clade, reads_taxon, rank, taxid, name
        """
        # Try multiple possible file patterns
        possible_patterns = [
            f"{sample}.kreport2.txt",
            f"{sample}.kreport2",
            f"{sample}.kraken2.report.txt",
            f"{sample}_kraken2.report",
            f"{sample}.report",
        ]

        report_path = None
        for pattern in possible_patterns:
            test_path = self.kraken2_dir / pattern
            if self.file_exists_with_retry(str(test_path)):
                report_path = test_path
                break

        if report_path is None:
            logger.warning(f"Kraken2 report not found for sample: {sample}")
            return pd.DataFrame(columns=['percent', 'reads_clade', 'reads_taxon', 'rank', 'taxid', 'name'])

        try:
            df = pd.read_csv(
                report_path,
                sep='\t',
                header=None,
                names=['percent', 'reads_clade', 'reads_taxon', 'rank', 'taxid', 'name']
            )

            # Clean up name column (remove leading spaces that indicate hierarchy)
            df['name'] = df['name'].str.strip()

            logger.info(f"Parsed Kraken2 report for {sample}: {len(df)} taxa")
            return df

        except Exception as e:
            logger.error(f"Error parsing Kraken2 report for {sample}: {e}")
            return pd.DataFrame(columns=['percent', 'reads_clade', 'reads_taxon', 'rank', 'taxid', 'name'])

    def parse_kraken_output(self, sample: str) -> Dict[int, int]:
        """
        Parse Kraken2 output file (per-read classifications).

        This parses the full Kraken2 output format with per-read assignments
        and returns aggregated counts per taxonomy ID.

        Args:
            sample: Sample name

        Returns:
            Dictionary mapping taxid to read counts
        """
        # Try multiple possible file patterns
        possible_patterns = [
            f"{sample}.kraken2",
            f"{sample}.kraken2.output.txt",
            f"{sample}_kraken2.output",
            f"{sample}.output",
        ]

        output_path = None
        for pattern in possible_patterns:
            test_path = self.kraken2_dir / pattern
            if self.file_exists_with_retry(str(test_path)):
                output_path = test_path
                break

        if output_path is None:
            logger.warning(f"Kraken2 output not found for sample: {sample}")
            return {}

        try:
            taxid_counts = {}

            with open(output_path, 'r') as f:
                for line in f:
                    parts = line.strip().split('\t')
                    if len(parts) >= 3:
                        # Kraken2 output format: C/U, sequence_id, taxid, ...
                        classified = parts[0]
                        taxid = int(parts[2]) if parts[2].isdigit() else 0

                        if classified == 'C':  # Classified read
                            taxid_counts[taxid] = taxid_counts.get(taxid, 0) + 1

            logger.info(f"Parsed Kraken2 output for {sample}: {len(taxid_counts)} unique taxa")
            return taxid_counts

        except Exception as e:
            logger.error(f"Error parsing Kraken2 output for {sample}: {e}")
            return {}

    def combine_kraken_reports(self) -> pd.DataFrame:
        """
        Combine Kraken2 reports from all samples.

        Aggregates classification results across all samples in the pipeline run.
        Prioritizes cumulative reports over standard reports to avoid
        double-counting reads from both batch and cumulative sources.

        Returns:
            DataFrame with aggregated Kraken2 reports, indexed by sample name
        """
        all_reports = []

        # First, check for cumulative reports (preferred in realtime mode).
        # These already contain aggregated data per sample, so loading both
        # a cumulative and a standard report would double-count reads.
        cumulative_files = list(self.kraken2_dir.glob('*.cumulative.kraken2.report.txt'))

        if cumulative_files:
            report_files = cumulative_files
            logger.debug(f"Using {len(cumulative_files)} cumulative Kraken2 reports")
        else:
            # Fall back to standard report patterns
            report_patterns = [
                '*.kreport2.txt', '*.kreport2', '*.kraken2.report.txt',
                '*_kraken2.report', '*.report',
            ]
            report_files_set: set = set()
            for pattern in report_patterns:
                for f in self.kraken2_dir.glob(pattern):
                    # Exclude batch files -- they are subsets of cumulative/standard reports
                    basename = f.name
                    if '_batch' not in basename and '.batch_' not in basename and not basename.startswith('batch_'):
                        report_files_set.add(f.resolve())
            report_files = list(report_files_set)

        if not report_files:
            logger.warning("No Kraken2 reports found")
            return pd.DataFrame()

        # Deduplicate by resolved path to avoid loading the same file twice
        # when multiple glob patterns match the same file
        seen_paths: set = set()
        seen_samples: set = set()

        for report_file in report_files:
            resolved = report_file.resolve()
            if resolved in seen_paths:
                continue
            seen_paths.add(resolved)

            # Extract sample name from filename
            sample_name = report_file.stem
            sample_name = re.sub(r'\.(cumulative\.kraken2\.report|kreport2|kraken2\.report|report)$', '', sample_name)

            # Only load one report per sample to prevent double-counting
            if sample_name in seen_samples:
                logger.debug(f"Skipping duplicate report for sample {sample_name}: {report_file}")
                continue
            seen_samples.add(sample_name)

            try:
                df = self.parse_kraken_report(sample_name)
                if not df.empty:
                    df['sample'] = sample_name
                    all_reports.append(df)
            except Exception as e:
                logger.error(f"Error parsing report {report_file}: {e}")
                continue

        if not all_reports:
            logger.warning("No valid Kraken2 reports parsed")
            return pd.DataFrame()

        combined_df = pd.concat(all_reports, ignore_index=True)
        logger.info(f"Combined {len(all_reports)} Kraken2 reports: {len(combined_df)} total entries")

        return combined_df

    def get_species_read_counts(self, species_taxids: List[str]) -> Dict[str, int]:
        """
        Get read counts for specific species taxonomy IDs across all samples.

        Args:
            species_taxids: List of NCBI taxonomy IDs to query

        Returns:
            Dictionary mapping taxid to total read count across all samples
        """
        combined_reports = self.combine_kraken_reports()

        if combined_reports.empty:
            return {taxid: 0 for taxid in species_taxids}

        # Convert taxids to integers for matching
        taxid_ints = [int(tid) for tid in species_taxids]

        # Filter for species rank and requested taxids
        species_data = combined_reports[
            (combined_reports['rank'] == 'S') &
            (combined_reports['taxid'].isin(taxid_ints))
        ]

        # Sum reads by taxid across all samples
        counts = {}
        for taxid in species_taxids:
            taxid_int = int(taxid)
            total_reads = species_data[species_data['taxid'] == taxid_int]['reads_clade'].sum()
            counts[taxid] = int(total_reads)

        logger.info(f"Retrieved read counts for {len(species_taxids)} species")
        return counts

    def get_top_species(self, n: int = 10) -> pd.DataFrame:
        """
        Get top N species by read count across all samples.

        Args:
            n: Number of top species to return

        Returns:
            DataFrame with top species sorted by read count
        """
        combined_reports = self.combine_kraken_reports()

        if combined_reports.empty:
            return pd.DataFrame(columns=['taxid', 'name', 'total_reads', 'samples'])

        # Filter for species rank only (no copy needed - used for groupby only)
        species_data = combined_reports[combined_reports['rank'] == 'S']

        if species_data.empty:
            logger.warning("No species-level classifications found")
            return pd.DataFrame(columns=['taxid', 'name', 'total_reads', 'samples'])

        # Aggregate by taxid
        top_species = species_data.groupby(['taxid', 'name']).agg({
            'reads_clade': 'sum',
            'sample': lambda x: list(x.unique())
        }).reset_index()

        top_species.columns = ['taxid', 'name', 'total_reads', 'samples']
        top_species['num_samples'] = top_species['samples'].apply(len)

        # Sort by total reads and take top N
        top_species = top_species.sort_values('total_reads', ascending=False).head(n)

        logger.info(f"Retrieved top {n} species")
        return top_species

    # ==================== FASTP Parsers ====================

    def parse_fastp_report(self, sample: str) -> Dict[str, Any]:
        """
        Parse FASTP JSON report for a specific sample.

        Args:
            sample: Sample name

        Returns:
            Dictionary with FASTP JSON structure
        """
        # Try multiple possible file patterns
        possible_patterns = [
            f"{sample}.fastp.json",
            f"{sample}_fastp.json",
            f"{sample}.json",
        ]

        report_path = None
        for pattern in possible_patterns:
            test_path = self.fastp_dir / pattern
            if self.file_exists_with_retry(str(test_path)):
                report_path = test_path
                break

        if report_path is None:
            logger.warning(f"FASTP report not found for sample: {sample}")
            return {}

        try:
            with open(report_path, 'r') as f:
                data = json.load(f)

            logger.info(f"Parsed FASTP report for {sample}")
            return data

        except Exception as e:
            logger.error(f"Error parsing FASTP report for {sample}: {e}")
            return {}

    def combine_fastp_reports(self) -> pd.DataFrame:
        """
        Combine FASTP reports from all samples.

        Returns:
            DataFrame with aggregated FASTP statistics
        """
        all_reports = []

        # Find all FASTP JSON files, deduplicating by resolved path to avoid
        # counting the same file twice when matched by multiple patterns
        json_files_set: set = set()
        for pattern in ['*.fastp.json', '*_fastp.json']:
            for f in self.fastp_dir.glob(pattern):
                json_files_set.add(f.resolve())
        json_files = [Path(f) for f in json_files_set]

        if not json_files:
            logger.warning("No FASTP reports found")
            return pd.DataFrame()

        seen_samples: set = set()

        for json_file in json_files:
            # Extract sample name from filename
            sample_name = json_file.stem
            sample_name = re.sub(r'(_fastp|\.fastp)$', '', sample_name)

            # Only load one report per sample to prevent double-counting
            if sample_name in seen_samples:
                logger.debug(f"Skipping duplicate FASTP report for sample {sample_name}")
                continue
            seen_samples.add(sample_name)

            try:
                data = self.parse_fastp_report(sample_name)
                if not data:
                    continue

                # Extract key metrics
                summary = data.get('summary', {})
                before = summary.get('before_filtering', {})
                after = summary.get('after_filtering', {})
                filtering = data.get('filtering_result', {})

                report_dict = {
                    'sample': sample_name,
                    'total_reads_before': before.get('total_reads', 0),
                    'total_bases_before': before.get('total_bases', 0),
                    'q20_rate_before': before.get('q20_rate', 0),
                    'q30_rate_before': before.get('q30_rate', 0),
                    'gc_content_before': before.get('gc_content', 0),
                    'total_reads_after': after.get('total_reads', 0),
                    'total_bases_after': after.get('total_bases', 0),
                    'q20_rate_after': after.get('q20_rate', 0),
                    'q30_rate_after': after.get('q30_rate', 0),
                    'gc_content_after': after.get('gc_content', 0),
                    'passed_filter_reads': filtering.get('passed_filter_reads', 0),
                    'low_quality_reads': filtering.get('low_quality_reads', 0),
                    'too_short_reads': filtering.get('too_short_reads', 0),
                }

                all_reports.append(report_dict)

            except Exception as e:
                logger.error(f"Error parsing FASTP report {json_file}: {e}")
                continue

        if not all_reports:
            logger.warning("No valid FASTP reports parsed")
            return pd.DataFrame()

        df = pd.DataFrame(all_reports)
        logger.info(f"Combined {len(all_reports)} FASTP reports")

        return df

    def get_fastp_summary(self) -> Dict[str, Any]:
        """
        Get summary statistics across all FASTP reports.

        Returns:
            Dictionary with total reads before/after filtering and quality metrics
        """
        combined_reports = self.combine_fastp_reports()

        if combined_reports.empty:
            return {
                'total_samples': 0,
                'total_reads_before': 0,
                'total_reads_after': 0,
                'total_bases_before': 0,
                'total_bases_after': 0,
                'avg_q20_rate_before': 0.0,
                'avg_q30_rate_before': 0.0,
                'avg_q20_rate_after': 0.0,
                'avg_q30_rate_after': 0.0,
                'total_passed_filter': 0,
                'total_low_quality': 0,
                'total_too_short': 0,
            }

        summary = {
            'total_samples': len(combined_reports),
            'total_reads_before': int(combined_reports['total_reads_before'].sum()),
            'total_reads_after': int(combined_reports['total_reads_after'].sum()),
            'total_bases_before': int(combined_reports['total_bases_before'].sum()),
            'total_bases_after': int(combined_reports['total_bases_after'].sum()),
            'avg_q20_rate_before': float(combined_reports['q20_rate_before'].mean()),
            'avg_q30_rate_before': float(combined_reports['q30_rate_before'].mean()),
            'avg_q20_rate_after': float(combined_reports['q20_rate_after'].mean()),
            'avg_q30_rate_after': float(combined_reports['q30_rate_after'].mean()),
            'total_passed_filter': int(combined_reports['passed_filter_reads'].sum()),
            'total_low_quality': int(combined_reports['low_quality_reads'].sum()),
            'total_too_short': int(combined_reports['too_short_reads'].sum()),
        }

        logger.info(f"Generated FASTP summary for {summary['total_samples']} samples")
        return summary

    # ==================== BLAST Parsers ====================

    def parse_blast_results(self, sample: str, taxid: str = None) -> pd.DataFrame:
        """
        Parse BLAST results for a specific sample.

        BLAST outfmt 6 (tabular) format with 12 columns:
        qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore

        Args:
            sample: Sample name
            taxid: Optional taxonomy ID filter

        Returns:
            DataFrame with BLAST hits
        """
        # Try multiple possible file patterns
        if taxid:
            possible_patterns = [
                f"{sample}_{taxid}.blast.txt",
                f"{sample}_{taxid}_blast.txt",
                f"{sample}.{taxid}.blast",
            ]
        else:
            possible_patterns = [
                f"{sample}.blast.txt",
                f"{sample}_blast.txt",
                f"{sample}.blast",
            ]

        blast_path = None
        for pattern in possible_patterns:
            test_path = self.blast_dir / pattern
            if self.file_exists_with_retry(str(test_path)):
                blast_path = test_path
                break

        if blast_path is None:
            logger.warning(f"BLAST results not found for sample: {sample}" +
                          (f", taxid: {taxid}" if taxid else ""))
            return pd.DataFrame(columns=[
                'qseqid', 'sseqid', 'pident', 'length', 'mismatch', 'gapopen',
                'qstart', 'qend', 'sstart', 'send', 'evalue', 'bitscore'
            ])

        try:
            df = pd.read_csv(
                blast_path,
                sep='\t',
                header=None,
                names=[
                    'qseqid', 'sseqid', 'pident', 'length', 'mismatch', 'gapopen',
                    'qstart', 'qend', 'sstart', 'send', 'evalue', 'bitscore'
                ]
            )

            logger.info(f"Parsed BLAST results for {sample}: {len(df)} hits")
            return df

        except Exception as e:
            logger.error(f"Error parsing BLAST results for {sample}: {e}")
            return pd.DataFrame(columns=[
                'qseqid', 'sseqid', 'pident', 'length', 'mismatch', 'gapopen',
                'qstart', 'qend', 'sstart', 'send', 'evalue', 'bitscore'
            ])

    def get_blast_validation_summary(self) -> Dict[str, Any]:
        """
        Get summary statistics for BLAST validation across all samples.

        Returns:
            Dictionary with validation statistics including hit counts and identity metrics
        """
        # Find all BLAST result files, deduplicating by resolved path
        blast_files_set: set = set()
        for pattern in ['*.blast.txt', '*_blast.txt']:
            for f in self.blast_dir.glob(pattern):
                blast_files_set.add(f.resolve())
        blast_files = [Path(f) for f in blast_files_set]

        if not blast_files:
            logger.warning("No BLAST results found")
            return {
                'total_samples': 0,
                'total_hits': 0,
                'avg_identity': 0.0,
                'avg_length': 0.0,
                'avg_evalue': 0.0,
            }

        all_hits = []
        samples = set()

        for blast_file in blast_files:
            # Extract sample name
            sample_name = blast_file.stem
            sample_name = re.sub(r'(_blast|\.blast)$', '', sample_name)
            samples.add(sample_name)

            try:
                df = pd.read_csv(
                    blast_file,
                    sep='\t',
                    header=None,
                    names=[
                        'qseqid', 'sseqid', 'pident', 'length', 'mismatch', 'gapopen',
                        'qstart', 'qend', 'sstart', 'send', 'evalue', 'bitscore'
                    ]
                )

                if not df.empty:
                    all_hits.append(df)

            except Exception as e:
                logger.error(f"Error parsing BLAST file {blast_file}: {e}")
                continue

        if not all_hits:
            return {
                'total_samples': len(samples),
                'total_hits': 0,
                'avg_identity': 0.0,
                'avg_length': 0.0,
                'avg_evalue': 0.0,
            }

        combined_df = pd.concat(all_hits, ignore_index=True)

        summary = {
            'total_samples': len(samples),
            'total_hits': len(combined_df),
            'avg_identity': float(combined_df['pident'].mean()),
            'avg_length': float(combined_df['length'].mean()),
            'avg_evalue': float(combined_df['evalue'].mean()),
            'min_identity': float(combined_df['pident'].min()),
            'max_identity': float(combined_df['pident'].max()),
            'min_evalue': float(combined_df['evalue'].min()),
            'max_evalue': float(combined_df['evalue'].max()),
        }

        logger.info(f"Generated BLAST validation summary: {summary['total_hits']} hits from {summary['total_samples']} samples")
        return summary

    # ==================== Real-time Batch Parsers ====================

    def parse_batch_stats(self, batch_number: int) -> Dict[str, Any]:
        """
        Parse real-time batch statistics for a specific batch.

        Args:
            batch_number: Batch number to parse

        Returns:
            Dictionary with batch JSON data
        """
        batch_file = self.realtime_batch_dir / f"batch_{batch_number:04d}_stats.json"

        try:
            if not self.file_exists_with_retry(str(batch_file)):
                logger.warning(f"Batch stats not found for batch {batch_number}")
                return {}

            with open(batch_file, 'r') as f:
                data = json.load(f)

            logger.debug(f"Parsed batch stats for batch {batch_number}")
            return data

        except Exception as e:
            logger.error(f"Error parsing batch {batch_number} stats: {e}")
            return {}

    def get_latest_batch_number(self) -> int:
        """
        Get the latest batch number from real-time processing.

        Returns:
            Latest batch number, or 0 if no batches found
        """
        if not self.realtime_batch_dir.exists():
            return 0

        try:
            batch_files = list(self.realtime_batch_dir.glob("batch_*_stats.json"))

            if not batch_files:
                return 0

            # Extract batch numbers from filenames
            batch_numbers = []
            for batch_file in batch_files:
                match = re.search(r'batch_(\d+)_stats\.json', batch_file.name)
                if match:
                    batch_numbers.append(int(match.group(1)))

            return max(batch_numbers) if batch_numbers else 0

        except Exception as e:
            logger.error(f"Error getting latest batch number: {e}")
            return 0

    def parse_all_batch_stats(self) -> List[Dict[str, Any]]:
        """
        Parse all available batch statistics.

        Returns:
            List of dictionaries containing all batch data
        """
        if not self.realtime_batch_dir.exists():
            logger.warning("Real-time batch directory does not exist")
            return []

        try:
            batch_files = sorted(self.realtime_batch_dir.glob("batch_*_stats.json"))

            if not batch_files:
                logger.warning("No batch stats files found")
                return []

            all_batches = []
            for batch_file in batch_files:
                try:
                    with open(batch_file, 'r') as f:
                        data = json.load(f)
                        all_batches.append(data)
                except Exception as e:
                    logger.error(f"Error parsing batch file {batch_file}: {e}")
                    continue

            logger.info(f"Parsed {len(all_batches)} batch statistics files")
            return all_batches

        except Exception as e:
            logger.error(f"Error parsing batch stats: {e}")
            return []

    def get_cumulative_stats(self) -> Dict[str, Any]:
        """
        Get cumulative statistics across all batches.

        Returns:
            Dictionary with totals across all batches including reads, classifications, etc.
        """
        all_batches = self.parse_all_batch_stats()

        if not all_batches:
            return {
                'total_batches': 0,
                'total_files': 0,
                'total_reads': 0,
                'total_classified': 0,
                'total_unclassified': 0,
                'classification_rate': 0.0,
                'first_batch_time': None,
                'last_batch_time': None,
            }

        cumulative = {
            'total_batches': len(all_batches),
            'total_files': sum(b.get('files_in_batch', 0) for b in all_batches),
            'total_reads': sum(b.get('reads_in_batch', 0) for b in all_batches),
            'total_classified': sum(b.get('classified_in_batch', 0) for b in all_batches),
            'total_unclassified': sum(b.get('unclassified_in_batch', 0) for b in all_batches),
        }

        # Calculate classification rate
        if cumulative['total_reads'] > 0:
            cumulative['classification_rate'] = (
                cumulative['total_classified'] / cumulative['total_reads']
            )
        else:
            cumulative['classification_rate'] = 0.0

        # Get time range
        timestamps = [b.get('timestamp') for b in all_batches if b.get('timestamp')]
        if timestamps:
            cumulative['first_batch_time'] = min(timestamps)
            cumulative['last_batch_time'] = max(timestamps)
        else:
            cumulative['first_batch_time'] = None
            cumulative['last_batch_time'] = None

        logger.info(f"Generated cumulative stats: {cumulative['total_reads']} reads across {cumulative['total_batches']} batches")
        return cumulative

    # ==================== Summary Methods ====================

    def get_classification_summary(self) -> Dict[str, Any]:
        """
        Get overall classification summary across all samples and tools.

        Combines data from Kraken2, FASTP, and real-time batches to provide
        a comprehensive overview of classification performance.

        Returns:
            Dictionary with classified/unclassified totals and classification rates
        """
        summary = {
            'kraken2': {},
            'fastp': {},
            'realtime': {},
            'overall': {},
        }

        # Kraken2 classification summary
        try:
            combined_kraken = self.combine_kraken_reports()
            if not combined_kraken.empty:
                # Get unclassified reads (rank 'U')
                unclassified = combined_kraken[combined_kraken['rank'] == 'U']['reads_clade'].sum()
                # Get root reads (rank 'R') which represents classified
                classified = combined_kraken[combined_kraken['rank'] == 'R']['reads_clade'].sum()

                summary['kraken2'] = {
                    'total_reads': int(classified + unclassified),
                    'classified': int(classified),
                    'unclassified': int(unclassified),
                    'classification_rate': float(classified / (classified + unclassified)) if (classified + unclassified) > 0 else 0.0,
                }
        except Exception as e:
            logger.error(f"Error computing Kraken2 classification summary: {e}")

        # FASTP summary
        try:
            fastp_summary = self.get_fastp_summary()
            summary['fastp'] = fastp_summary
        except Exception as e:
            logger.error(f"Error computing FASTP summary: {e}")

        # Real-time batch summary
        try:
            cumulative_stats = self.get_cumulative_stats()
            summary['realtime'] = cumulative_stats
        except Exception as e:
            logger.error(f"Error computing real-time summary: {e}")

        # Overall summary (prefer Kraken2 for classification stats)
        if summary['kraken2']:
            summary['overall'] = summary['kraken2']
        elif summary['realtime']:
            summary['overall'] = {
                'total_reads': summary['realtime'].get('total_reads', 0),
                'classified': summary['realtime'].get('total_classified', 0),
                'unclassified': summary['realtime'].get('total_unclassified', 0),
                'classification_rate': summary['realtime'].get('classification_rate', 0.0),
            }
        else:
            summary['overall'] = {
                'total_reads': 0,
                'classified': 0,
                'unclassified': 0,
                'classification_rate': 0.0,
            }

        logger.info("Generated comprehensive classification summary")
        return summary


class RealtimeMonitor:
    """
    Monitor for new batch statistics in real-time processing mode.

    This class implements a polling-based monitoring system that detects
    new batch statistics files and triggers callbacks for real-time dashboard updates.

    Attributes:
        parser (NanometanfOutputParser): Parser instance for reading batch data
        update_callback (Callable): Function to call when new data is detected
        monitoring (bool): Whether monitoring is currently active
        last_batch_number (int): Last processed batch number
        monitor_thread (threading.Thread): Background monitoring thread
    """

    def __init__(self, outdir: str, update_callback: Callable[[Dict[str, Any]], None]):
        """
        Initialize the real-time monitor.

        Args:
            outdir: Pipeline output directory
            update_callback: Function to call with new batch data
        """
        self.parser = NanometanfOutputParser(outdir)
        self.update_callback = update_callback
        self.monitoring = False
        self.last_batch_number = 0
        self.monitor_thread = None

        logger.info(f"Initialized RealtimeMonitor for {outdir}")

    def _monitor_loop(self, interval: int):
        """
        Internal monitoring loop that runs in background thread.

        Args:
            interval: Polling interval in seconds
        """
        logger.info(f"Starting monitoring loop with {interval}s interval")

        # Get initial batch number
        self.last_batch_number = self.parser.get_latest_batch_number()
        logger.info(f"Initial batch number: {self.last_batch_number}")

        while self.monitoring:
            try:
                current_batch = self.parser.get_latest_batch_number()

                # Check if new batches are available
                if current_batch > self.last_batch_number:
                    logger.info(f"New batches detected: {self.last_batch_number + 1} to {current_batch}")

                    # Process all new batches
                    for batch_num in range(self.last_batch_number + 1, current_batch + 1):
                        batch_data = self.parser.parse_batch_stats(batch_num)

                        if batch_data:
                            try:
                                self.update_callback(batch_data)
                                logger.debug(f"Callback executed for batch {batch_num}")
                            except Exception as e:
                                logger.error(f"Error in update callback for batch {batch_num}: {e}")

                    self.last_batch_number = current_batch

                # Sleep for the specified interval
                time.sleep(interval)

            except Exception as e:
                logger.error(f"Error in monitoring loop: {e}")
                time.sleep(interval)

    def start_monitoring(self, interval: int = 10):
        """
        Start monitoring for new batch statistics.

        Args:
            interval: Polling interval in seconds (default: 10)
        """
        if self.monitoring:
            logger.warning("Monitoring already active")
            return

        self.monitoring = True
        self.monitor_thread = threading.Thread(
            target=self._monitor_loop,
            args=(interval,),
            daemon=True
        )
        self.monitor_thread.start()

        logger.info(f"Started monitoring with {interval}s interval")

    def stop_monitoring(self):
        """
        Stop monitoring for new batch statistics.
        """
        if not self.monitoring:
            logger.warning("Monitoring not active")
            return

        logger.info("Stopping monitoring")
        self.monitoring = False

        if self.monitor_thread:
            self.monitor_thread.join(timeout=5)
            logger.info("Monitoring stopped")
