"""Scientific assertions against a real run over the Bioshield truth set.

Every other test in this suite uses synthetic fixtures. Those prove the code
does what it was written to do; they cannot prove it produces the right
biological answer, because the expected output is generated by the same
assumptions as the code. These tests use ONT reads from samples whose contents
are known independently of this software.

Sample map (see tests/realdata/README.md):

===========  ===========================================================
barcode11    Francisella tularensis LVS -- a Tier 1 select agent, NCBI
             taxid 263. The positive control for the product's core claim.
barcode14    ZymoBIOMICS D6300 mock community -- 8 bacteria, 2 yeasts at
             known nominal abundances.
barcode16    Negative control -- no template.
===========  ===========================================================

Run with::

    NANOMETA_REALDATA_DIR=/path/to/results pytest tests/realdata -v
"""

from __future__ import annotations

import pytest

from .kreport import Report

pytestmark = pytest.mark.integration

#: Francisella tularensis. cdc_bioterrorism.yaml lists it threat_level
#: "critical", BSL-3, HHS-SA-Tier1, alert_threshold 5.
TULARENSIS = 263

#: ZymoBIOMICS D6300 members, by NCBI species taxid. Eight bacteria and two
#: yeasts, nominally 12% each for the bacteria and 2% each for the yeasts.
#:
#: Use species taxids, not genus: 590 is the genus Salmonella, 28901 is
#: S. enterica. Asserting on the genus would pass even if the species call
#: were wrong.
D6300_BACTERIA = {
    287: "Pseudomonas aeruginosa",
    562: "Escherichia coli",
    28901: "Salmonella enterica",
    1613: "Limosilactobacillus fermentum",
    1351: "Enterococcus faecalis",
    1280: "Staphylococcus aureus",
    1639: "Listeria monocytogenes",
    1423: "Bacillus subtilis",
}
D6300_YEASTS = {
    4932: "Saccharomyces cerevisiae",
    5207: "Cryptococcus neoformans",
}
D6300_MEMBERS = {**D6300_BACTERIA, **D6300_YEASTS}


def _report(kraken_reports, sample) -> Report:
    if sample not in kraken_reports:
        pytest.skip(f"{sample} not present in this run ({sorted(kraken_reports)})")
    return Report.from_file(kraken_reports[sample])


class TestPositiveControl:
    """barcode11 carries F. tularensis LVS and the pipeline must find it."""

    def test_tularensis_is_detected(self, kraken_reports):
        report = _report(kraken_reports, "barcode11")
        reads = report.reads_for(TULARENSIS)
        assert reads > 0, (
            "Francisella tularensis (taxid 263) was not detected in the LVS "
            "positive control. This is the product's central claim: if a Tier 1 "
            "select agent present at high abundance is missed, nothing else in "
            "the dashboard matters."
        )

    def test_tularensis_is_the_dominant_organism(self, kraken_reports):
        """LVS is a near-pure culture, so it should lead by a wide margin."""
        report = _report(kraken_reports, "barcode11")
        top = report.top_species(1)
        assert top, "no species-rank rows in the positive control"
        assert top[0].taxid == TULARENSIS, (
            f"the most abundant species in the LVS control is "
            f"{top[0].name!r} (taxid {top[0].taxid}, {top[0].cumulative_reads} "
            f"reads), not F. tularensis. Either the sample is mislabelled or "
            f"classification is misassigning the dominant organism."
        )

    def test_named_not_just_numbered(self, kraken_reports):
        """A taxid with no name renders as a blank row in the dashboard."""
        report = _report(kraken_reports, "barcode11")
        row = report.by_taxid(TULARENSIS)
        assert row is not None and row.name.strip(), (
            "taxid 263 resolved to an empty name; the operator would see a "
            "detection with no organism against it"
        )
        assert "francisella" in row.name.lower(), (
            f"taxid 263 is named {row.name!r}, which is not F. tularensis"
        )


class TestNegativeControl:
    """barcode16 has no template. What it does contain is the noise floor."""

    def test_negative_control_is_not_dominated_by_real_signal(self, kraken_reports):
        """A sanity bound, deliberately loose.

        The negative control is not expected to be empty -- index hopping,
        reagent contamination and misclassification all put a handful of reads
        in it. It is expected to be *shallow*. If it carries a substantial
        fraction of the positive control's depth, the demultiplexing is wrong.
        """
        negative = _report(kraken_reports, "barcode16")
        if "barcode11" not in kraken_reports:
            pytest.skip("needs the positive control for a depth comparison")
        positive = _report(kraken_reports, "barcode11")

        assert positive.classified_reads > 0, "positive control classified nothing"
        ratio = negative.classified_reads / positive.classified_reads
        assert ratio < 0.01, (
            f"the negative control holds {negative.classified_reads} classified "
            f"reads against the positive control's {positive.classified_reads} "
            f"({ratio:.1%}). At that depth the barcodes are not cleanly "
            f"separated and per-sample attribution cannot be trusted."
        )

    @pytest.mark.xfail(
        reason=(
            "Known and measured, not yet decided. Run R1 (2026-07-28) put 6 "
            "F. tularensis reads in the negative control against an "
            "alert_threshold of 5, so a blank sample raises a CRITICAL alert. "
            "Runs R1 and R7 agree exactly (see "
            "TestCrossRun.test_multiplexing_does_not_add_select_agent_reads), "
            "which rules out barcode leakage in this software: the reads are "
            "in the FASTQ, from lab-side index hopping at 0.018% of the "
            "positive control's depth. The open question is whether an "
            "absolute read-count threshold is the right rule at all, since it "
            "cannot distinguish 6-of-11 reads in a near-empty sample from 6 "
            "reads in a deep one. Remove this xfail when the threshold policy "
            "is settled."
        ),
        strict=False,
    )
    def test_select_agent_reads_stay_below_the_alert_threshold(self, kraken_reports):
        """The operational claim: a clean sample must not raise a CRITICAL alert.

        A detector that cries wolf on a blank is worse than no detector,
        because it trains the operator to dismiss it.
        """
        report = _report(kraken_reports, "barcode16")
        reads = report.reads_for(TULARENSIS)
        assert reads < 5, (
            f"the negative control carries {reads} reads of F. tularensis, at "
            f"or above the alert_threshold of 5 for this Tier 1 select agent. "
            f"As configured, this sample raises a CRITICAL alert."
        )


class TestCrossRun:
    """Comparisons between two runs of the same sample under different company.

    Set NANOMETA_REALDATA_COMPARE_DIR to a second results tree in which the
    negative control was processed *alone*. Together with the multiplexed run
    this separates two indistinguishable-from-one-run explanations for select
    agent reads in a blank: contamination already present in the FASTQ, versus
    this software leaking reads across barcodes.
    """

    def test_multiplexing_does_not_add_select_agent_reads(
        self, kraken_reports, compare_kraken_reports
    ):
        """The software claim, and the only one this project controls.

        If the negative control yields more F. tularensis when it is
        multiplexed alongside a high-titre LVS sample than when it runs on its
        own, reads are crossing barcodes somewhere in this pipeline -- a
        release blocker, and invisible to every synthetic test. Equal counts
        mean the reads were in the input file and the pipeline reported them
        faithfully.
        """
        multiplexed = _report(kraken_reports, "barcode16")
        alone = Report.from_file(compare_kraken_reports["barcode16"])

        assert multiplexed.reads_for(TULARENSIS) == alone.reads_for(TULARENSIS), (
            f"the negative control gained "
            f"{multiplexed.reads_for(TULARENSIS) - alone.reads_for(TULARENSIS)} "
            f"F. tularensis reads by being run alongside other barcodes "
            f"({multiplexed.reads_for(TULARENSIS)} multiplexed vs "
            f"{alone.reads_for(TULARENSIS)} alone). Reads are crossing "
            f"barcodes inside the pipeline."
        )

    def test_classification_is_reproducible_across_runs(
        self, kraken_reports, compare_kraken_reports
    ):
        """The same input must classify identically regardless of run context."""
        multiplexed = _report(kraken_reports, "barcode16")
        alone = Report.from_file(compare_kraken_reports["barcode16"])
        assert multiplexed.classified_reads == alone.classified_reads, (
            f"the same FASTQ classified {multiplexed.classified_reads} reads in "
            f"one run and {alone.classified_reads} in another; classification "
            f"is not deterministic with respect to run composition"
        )

    def test_shared_samples_report_the_same_taxa(
        self, kraken_reports, compare_kraken_reports
    ):
        """Every sample common to both runs must yield the same taxon set.

        Pointed at a batch run and a realtime run of the same input, this is
        the batch-versus-realtime equivalence check. The two modes take
        genuinely different paths -- realtime classifies incrementally and
        accumulates into a cumulative report, batch classifies once -- so a
        divergence is a silent scientific bug: two operators analysing the
        same reads would brief different findings, and nothing in the suite
        would flag it.

        Compares taxa above a small read floor, because a single-read
        difference at the tail is noise rather than a mode difference.
        """
        floor = 5
        shared = sorted(set(kraken_reports) & set(compare_kraken_reports))
        if not shared:
            pytest.skip("the two runs share no sample names")

        divergent = {}
        for sample in shared:
            left = Report.from_file(kraken_reports[sample])
            right = Report.from_file(compare_kraken_reports[sample])
            left_taxa = {r.taxid for r in left.species() if r.cumulative_reads >= floor}
            right_taxa = {r.taxid for r in right.species() if r.cumulative_reads >= floor}
            if left_taxa != right_taxa:
                divergent[sample] = {
                    "only_in_first": sorted(left_taxa - right_taxa),
                    "only_in_second": sorted(right_taxa - left_taxa),
                }

        assert not divergent, (
            f"the two runs disagree on which taxa are present (at >= {floor} "
            f"reads): {divergent}"
        )


class TestMockCommunity:
    """barcode14 is ZymoBIOMICS D6300 at known composition."""

    def test_most_members_are_recovered(self, kraken_reports):
        """Not all ten: the two yeasts are under-represented on ONT and the
        database may lack them. Requiring all ten would make this test fail
        for a database choice rather than for a regression."""
        report = _report(kraken_reports, "barcode14")
        found = {t: report.reads_for(t) for t in D6300_MEMBERS}
        present = {t: n for t, n in found.items() if n > 0}
        missing = {D6300_MEMBERS[t]: t for t in found if found[t] == 0}
        assert len(present) >= 8, (
            f"only {len(present)} of 10 D6300 members were recovered; "
            f"missing: {missing}"
        )

    def test_the_eight_bacteria_are_all_present(self, kraken_reports):
        """The bacteria are abundant and well represented in any standard
        database, so all eight should appear.

        Their relative abundances are deliberately not asserted. The
        gram-positive members (B. subtilis, S. aureus, L. monocytogenes) are
        systematically under-recovered because they resist lysis, so observed
        proportions depart from the nominal 12% for reasons upstream of this
        software. Presence is the property this pipeline controls.
        """
        report = _report(kraken_reports, "barcode14")
        missing = {
            name: taxid
            for taxid, name in D6300_BACTERIA.items()
            if report.reads_for(taxid) == 0
        }
        assert not missing, (
            f"D6300 bacterial members absent from the classification: {missing}"
        )

    def test_no_select_agent_in_the_mock_community(self, kraken_reports):
        """D6300 contains no select agent. Finding one is a false positive."""
        report = _report(kraken_reports, "barcode14")
        reads = report.reads_for(TULARENSIS)
        assert reads < 5, (
            f"F. tularensis was called {reads} times in a mock community known "
            f"not to contain it, at or above the CRITICAL alert threshold"
        )


class TestReportIntegrity:
    """Structural properties that hold for any correct Kraken2 report."""

    def test_every_report_has_a_root(self, kraken_reports):
        for sample, path in kraken_reports.items():
            report = Report.from_file(path)
            assert report.by_taxid(1) is not None, (
                f"{sample}: report has no root (taxid 1) row, so the "
                f"sequences-analyzed tile has nothing to sum"
            )

    def test_no_sample_classified_zero_reads(self, kraken_reports):
        empty = [
            s for s, p in kraken_reports.items()
            if Report.from_file(p).classified_reads == 0
        ]
        assert not empty, (
            f"samples with zero classified reads: {empty}. A run that "
            f"completes successfully while classifying nothing shows the "
            f"operator an empty dashboard with no error."
        )

    def test_subspecies_never_exceed_their_species(self, kraken_reports):
        """Cumulative counts must nest. A subspecies row larger than its
        species means the report is being summed rather than read, which is
        the double-counting failure the abundance code guards against."""
        for sample, path in kraken_reports.items():
            report = Report.from_file(path)
            for sub in report.rows:
                if not sub.rank.startswith("S") or sub.rank == "S":
                    continue
                species = report.ancestor_at_rank(sub, "S")
                if species is None:
                    continue
                assert sub.cumulative_reads <= species.cumulative_reads, (
                    f"{sample}: {sub.name} ({sub.cumulative_reads} reads) "
                    f"exceeds its parent species {species.name} "
                    f"({species.cumulative_reads} reads)"
                )
